version: '2.1'

services:
    postgres:
        image: postgres:9.6
        environment:
            POSTGRES_USER: mg_telegram
            POSTGRES_PASSWORD: mg_telegram
            POSTGRES_DATABASE: mg_telegram
        ports:
            - ${POSTGRES_ADDRESS:-127.0.0.1:5434}:${POSTGRES_PORT:-5432}

    mg_telegram:
        image: golang:1.9.3-stretch
        working_dir: /mgtg
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - ./:/mgtg
            - ./static:/static/
        links:
            - postgres
        ports:
            - ${MG_TELEGRAM_ADDRESS:-3001}:3001
        command: make run
